package cutscenes;

import json.JSONObject;

public interface TextGenerator {
	
	/**
	 * Gets the text generated by this TextGenerator
	 * @return the text from this TextGenerator
	 */
	public String getText ();

	/**
	 * Sets the parameters for this TextGenerator
	 */
	public void setParams (JSONObject params);
	
	/**
	 * Gets the parameters for this TextGenerator
	 * @return the parameters for this TextGenerator, as a JSONObject
	 */
	public JSONObject getParams ();
}
